//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizLogic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class BizLogicSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static BizLogicSettings defaultInstance = ((BizLogicSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BizLogicSettings())));
        
        public static BizLogicSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
